name: Aplicação Django

on: [pull request]

jobs:
  build:
    env:
      PIPENV_NO_INHERIT: 1
      PIPENV_IGNORE_VIRTUALENVS: 1
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Instalar Dependências
        run: |
          pip install pipenv
          pipenv sync --dev
      - name: Rodar os testes automáticos
        run: |
          pipenv run pytest webdev
